version: "1"

services:
  - type: web
    name: n8n
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: N8N_USER_FOLDER
        value: /opt/render/.n8n
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: true
      - key: N8N_RUNNERS_ENABLED
        value: true
      - key: N8N_EXECUTIONS_MODE
        value: "queue"
      - key: N8N_HOST
        sync: false
      - key: N8N_EDITOR_BASE_URL
        sync: false

    healthCheckPath: /healthz
    autoDeploy: true
