version: "1"

services:
  - type: web
    name: n8n
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    startCommand: n8n start
  

    healthCheckPath: /healthz
    autoDeploy: true
